### ISSUE TITLE
how does it compare to flintlock?

### ISSUE THREAD

**Issue by PromptCoding** [vaccovecrana/frag-falcon#15]
wondering if this project is mature enough to use in production?

also how does this differ from https://github.com/liquidmetal-dev/flintlock?tab=readme-ov-file ?

can it work with cloudflare tunnel?

i want to know if i can host multiple docker alpine linux images via firecracker (each belonging to a user) securely with some sort of secure jailer

**Comment by jjzazuet** [comment]
Looks like this can be closed. Thanks!
